version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload



  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5864:5432"
#
#  flake8:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: flake8
#    volumes:
#      - .:/app
#    networks:
#      - backend
#    command: flake8 .
#  isort:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: isort
#    volumes:
#      - .:/app
#    networks:
#      - backend
#    command: isort . --check-only

volumes:
  postgres_data:
